name: khosousi_online
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  internet_connection_checker: ^1.0.0+1
  dartz: ^0.10.1
  get_it: ^7.6.7
  dio: ^5.4.3+1
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10+1
  flutter_staggered_grid_view: ^0.7.0
  youtube_player_flutter: ^9.0.0
  flutter_rating_bar: ^4.0.1
  readmore: ^2.2.0
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  extended_wrap: ^0.1.5
  flutter_spinkit: ^5.2.1
  persistent_bottom_nav_bar_v2: ^5.2.3
  lottie: ^3.1.0
  geolocator: ^12.0.0
  permission_handler: ^11.3.0
  syncfusion_flutter_charts: ^25.1.41+2
  flutter_html: 3.0.0-beta.2
  url_launcher: ^6.3.0
  html: ^0.15.4
  google_maps_flutter: ^2.7.0
  like_button: ^2.0.5
  flutter_dotenv: ^5.1.0
  device_info_plus: ^9.1.2
  badges: ^3.1.2
  image_picker: ^1.1.2
  fluttertoast: ^8.2.6
  pin_code_fields: ^8.0.1
  animated_floating_buttons: ^0.0.2
  easy_stepper: ^0.8.5
  pull_to_refresh: ^2.0.0
  mobkit_dashed_border: ^0.0.6





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo_foreground.png"






flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/authenticated.svg
    - assets/images/logo_black.png
    - assets/images/logo_white.png
    - assets/images/online_learning.json
    - assets/images/accepted.json
    - assets/images/warning.json
    - assets/images/google.png
    - assets/images/app_logo.png
    - assets/images/wallpaper.png
    - assets/images/operator.svg
    - assets/images/otp.svg
    - assets/config/.env
    - assets/images/forgot_password.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: DroidKufi
       fonts:
         - asset: assets/font/DroidKufi-Bold.ttf
         - asset: assets/font/DroidKufi-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
